name: ChristianPezza
favicon: null
layout_spectrum: 0.6979787268210202
typography_spectrum: 0.48396966722793877
title: Christian Pezza
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-79555555-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#63A69F'
    - '#F2E1AC'
    - '#F2836B'
    - '#F2594B'
    - '#CD2C24'
  brandStrength: 0.04513577511534095
  lightness: 0.9261860291007906
  saturation: 0.0013728495687246323
  rhythmicContrast: 0.7401391584426165
purpose: []
