name: ChristianPezza
favicon: null
layout_spectrum: 0.99819
typography_spectrum: 0.88143
title: Christian Pezza
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-79555555-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3d3a35'
    - '#00fffb'
    - '#d0b586'
    - '#768abf'
    - '#a2141d'
  brandStrength: 1
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
